stages:
  - build
  - docker
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - cd src/CommunicationControl
    - dotnet publish -c Release -p:PublishProfile=FolderProfile -o ./published DevOpsProject/DevOpsProject.CommunicationControl.API.csproj
  artifacts:
    paths:
      - src/CommunicationControl/published

docker-com-control:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - if [ "${CI_COMMIT_REF_NAME}" = "main" ];
      then
      export DOCKER_IMAGE_TAG=latest;
      elif [-v "${CI_COMMIT_TAG}"];
      then
      export DOCKER_IMAGE_TAG=["CI_COMMIT_TAG"];
      else
      export DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME};
      fi
    - cd src/CommunicationControl
    - docker build -t ${CI_REGISTRY}/kzotkin/hiveemulator/communication-control:${DOCKER_IMAGE_TAG} -f  DevOpsProject/Dockerfile .
    - docker push ${CI_REGISTRY}/kzotkin/hiveemulator/communication-control:${DOCKER_IMAGE_TAG}
  after_script:
    - docker logout ${CI_REGISTRY}

docker-map-client:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - if [ "${CI_COMMIT_REF_NAME}" = "main" ];
      then
      export DOCKER_IMAGE_TAG=latest;
      elif [-v "${CI_COMMIT_TAG}"];
      then
      export DOCKER_IMAGE_TAG=["CI_COMMIT_TAG"];
      else
      ex  port DOCKER_IMAGE_TAG=${CI_COMMIT_REF_NAME};
      fi
    - cd src/MapClient
    - npm install
    - npm run build
    - docker build -t ${CI_REGISTRY}/kzotkin/hiveemulator/map-client:${DOCKER_IMAGE_TAG} .
    - docker push ${CI_REGISTRY}/kzotkin/hiveemulator/map-client:${DOCKER_IMAGE_TAG}
  after_script:
    - docker logout ${CI_REGISTRY}

deploy_dev:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${DEV_KUB_SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${DEV_KUB_USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - kubectl rollout restart deployment/api
    - kubectl rollout restart deployment/notifications-service
    - kubectl rollout restart deployment/workers
  when: manual
  only:
    - current
