# serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-deployer-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin # Or a limited custom role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: gitlab-deployer
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-deployer-token
  annotations:
    kubernetes.io/service-account.name: gitlab-deployer
type: kubernetes.io/service-account-token
